### ISSUE TITLE
[QUESTION] Where to find `pubchem_rd-canonical_smiles.smi`?

### ISSUE THREAD

**Issue by jmatias** [IBM/materials#1]
I couldn't find in the source the link you used to build the `pubchem_rd-canonical_smiles` dataset. Do you have a link I could use?

**Comment by vichShir** [comment]
Although we were unable to open-source our curated dataset of 91 million molecules from PubChem, we can outline the steps taken to achieve it. Using the PubChem dataset from MoLFormer (https://ibm.ent.box.com/v/MoLFormer-data), we canonicalized the molecular strings and removed duplicates to ensure uniqueness. Following this, a molecular transformation process was applied to validate the molecules derived from the unique SMILES strings.

**Comment by vichShir** [comment]
I'm closing this issue because it has been inactive for 34 days.

Please, feel free to reopen this issue if it has been closed in error.
