### ISSUE TITLE
There is no fast_transformers folder in \materials\models\smi_ted\inference\smi_ted_light.

### ISSUE THREAD

**Issue by yueyue2299** [IBM/materials#19]
I used \materials\models\smi_ted\notebooks\smi_ted_encoder_decoder_example.ipynb and found that the folder does not exist in the inference path. I resolved this issue by copying and pasting another smi_ted_light folder to the location.

**Comment by vichShir** [comment]
Hi @yueyue2299! Thanks for pointing this out, I have fixed this in commit [d2d14a5](https://github.com/IBM/materials/commit/d2d14a570d38879a18dff3c3f5092256b27a224d). Please, feel free to reopen if it has been closed in error.
