### ISSUE TITLE
[QUESTION] Where to find `selfie-ted` and `3dgrid-vqgan`?

### ISSUE THREAD

**Issue by jmatias** [IBM/materials#2]
The read me makes mention of 3 models, but I'm only seeing the first `smi-ted` dir. Is that intentional?

```
materials/
├── smi-ted
├── selfie-ted
├── 3dgrid-vqgan
├── ...  
```

**Comment by vichShir** [comment]
Currently, only the SMI-TED model has been open-sourced. We are actively working on releasing additional models and will continue to provide updates as they become available.

**Comment by jmatias** [comment]
> Currently, only the SMI-TED model has been open-sourced. We are actively working on releasing additional models and will continue to provide updates as they become available.

Cool, thanks for getting back to me!

**Comment by vichShir** [comment]
I'm closing this issue because it has been inactive for 34 days.

Please, feel free to reopen this issue if it has been closed in error.
